services:
  - type: web
    name: myciti-bus-schedule
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app
    healthCheckPath: /api/health
